import React from 'react';

const PrintSummary = ({ workers, totalTips, tipPerHour, formatCurrency }) => {
  const totalHours = workers.reduce((sum, worker) => sum + worker.hours, 0);
  const totalWorkers = workers.length;
  const date = new Date().toLocaleDateString();

  return (
    <div className="print-summary">
      <div className="print-header">
        <h1>Tip Distribution Summary</h1>
        <p className="print-date">Date: {date}</p>
      </div>

      <div className="print-overview">
        <div className="overview-item">
          <span>Total Tips:</span>
          <strong>{formatCurrency(totalTips)}</strong>
        </div>
        <div className="overview-item">
          <span>Total Hours:</span>
          <strong>{totalHours.toFixed(2)}</strong>
        </div>
        <div className="overview-item">
          <span>Workers:</span>
          <strong>{totalWorkers}</strong>
        </div>
        <div className="overview-item">
          <span>Tips per Hour:</span>
          <strong>{formatCurrency(tipPerHour)}</strong>
        </div>
      </div>

      <table className="print-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Hours</th>
            <th>Rate</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          {workers.map((worker) => {
            const amount = worker.hours * worker.percentage * tipPerHour;
            return (
              <tr key={worker.id}>
                <td>{worker.name}</td>
                <td>{worker.hours}</td>
                <td>{worker.percentage === 0.7 ? '70%' : '100%'}</td>
                <td>{formatCurrency(amount)}</td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <div className="print-footer">
        <p>Generated by Restaurant Tip Calculator</p>
      </div>
    </div>
  );
};

export default PrintSummary;